name: main
on: [push]
jobs:
  build-appimage:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wget gcc g++ make pkg-config libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libopengl-dev libglx-dev libglu1-mesa-dev freeglut3-dev libxxf86vm-dev
      
      - name: Install Go
        run: |
          wget https://go.dev/dl/go1.22.3.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.22.3.linux-amd64.tar.gz

      - name: Install capstone
        run: |
          cd /tmp
          wget -q -O capstone.tar.gz https://github.com/capstone-engine/capstone/archive/5.0.1.tar.gz 
          tar xf capstone.tar.gz
          rm capstone.tar.gz
          cd capstone*
          sudo CAPSTONE_ARCHS=arm ./make.sh install

      - name: Build libinfiniemu
        run: make -j$(nproc) libinfiniemu.o

      - name: Build raw-viewer
        run: |
          cd tools/raw-viewer
          /usr/local/go/bin/go build .

      - name: Build AppImage
        run: |
          wget -q -O appimagetool.AppImage https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool.AppImage
          cd tools/raw-viewer
          mkdir -p AppDir/usr/bin AppDir/usr/lib
          cp raw-viewer AppDir/usr/bin
          cp /usr/lib/libcapstone.so.5 AppDir/usr/lib
          ./appimagetool.AppImage AppDir/

      - uses: actions/upload-artifact@v4
        with:
          name: InfiniEmu AppImage
          path: InfiniEmu-x86_64.AppImage
          if-no-files-found: error
